### ISSUE TITLE
If raider.io ws is unavailable the page cant be loaded

### ISSUE THREAD

**Issue by amarques** [domainzero/mythicpl.us#80]

**Comment by domainzero** [comment]
Finally got around to fixing this issue.
I cache the API results on Tuesday in the US and Wednesday in the EU and then serve those from the local server instead of calling the API on every page load.

I also split out the scripts that generate the affix listings at the top of the page from the scripts that load the dictionary so that the dictionary can load even if the `get-affixes` script breaks.
