### ISSUE TITLE
Small developer API

### ISSUE THREAD

**Issue by WKoppenol** [domainzero/mythicpl.us#90]
Heya, I'm currently in the process of writing a website which will be used for Mythic Plus and I thought of integrating it with mythicpl.us since I've used it extensively when I was doing M+ actively.

What I'd like to do is integrate the data on mythicpl.us on my site, notably the affix colors (difficulty) and what affixes there are every week. Possibly also affixes in general, I have them hard-coded now but if you made some API for it my website could be auto-updated by it.

Let me know what you think and we'll work something out. It doesn't feel right to rip your work off so I'm looking to collaborate :)

(should've used my other account for this, this is my 'professional' account, though it's empty. I'm /u/Wotuu on reddit/github)

**Comment by domainzero** [comment]
Hey! Thanks for your interest in the project.
As it stands right now I'm calling an [existing API](https://raider.io/api) (raider.io) to get the current affixes so you may be better suited to just call the same API for current affixes, etc.

Let me know if there's something else you want to do after you check out their API.

**Comment by Wotuu** [comment]
I did look at the raider.io API earlier, but forgot it existed, thanks! I will probably integrate that later for the Affix list. There is no schedule in the raider.io or known list of affixes per week. What I am interested in now is the difficulty of a specific affix which is gathered by mythicpl.us using user Survey. and that list per week. I've taken the list as it is since it's public knowledge at this point, but still looking to integrate with the difficulties if possible.
